### ISSUE TITLE
Updating the configuration sample in the README

### ISSUE THREAD

**Issue by mohsen-vybenetwork** [rpcpool/solana-accountsdb-plugin-kafka#27]
Hey guys, 

First and foremost, we want to express our gratitude for your outstanding support. I think due to recent updates and the introduction of support for multiple configuration filters, the existing configuration information in the README may be outdated and requires an update.

**Comment by fanatid** [comment]
Updated in https://github.com/rpcpool/solana-accountsdb-plugin-kafka/commit/bac1d517661db4fdedd8230e726577c1386a4669
